target 'BrotherVietnam' do
  use_frameworks!
	pod 'FacebookSDK'
  pod 'FacebookSDK/LoginKit'
  pod 'FacebookSDK/ShareKit'
  pod 'FacebookSDK/PlacesKit'
  pod 'FBSDKMessengerShareKit'
  pod 'AccountKit'
  pod 'SteviaLayout'
end
