# Uncomment the next line to define a global platform for your project

#source 'https://github.com/CocoaPods/Specs.git'
#platform :ios, '9.0'
target 'SocketIOClient' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Socket.IO-Client-Swift', '~> 15.0.0'
  pod 'Charts'
  pod 'SteviaLayout'
end
